events {
    #Number of requests nginx can handle at once
    worker_connections 1024;
}

http {
    
    
    server {
        listen 80;
        client_max_body_size 2G;
        location /api/ {
            #use docker service names and ports
            proxy_pass http://api:5000/;

        }


        location /videos/ {
            proxy_pass  http://minio:9000/videos/;
            proxy_set_header Host minio:9000;
         
        }
    }

} 

rtmps {

    server{
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;
        }
    }
}
 
