events {
    #Number of requests nginx can handle at once
    worker_connections 1024;
}

http {
    
    
    server {
        listen 80;
        client_max_body_size 2G;
        location /api/ {
            #use docker service names and ports
            proxy_pass http://api:5000/;

        }


        location /videos/ {
            proxy_pass  http://minio:9000/videos/;
            proxy_set_header Host minio:9000;
         
        }
        location /live/ {
            alias /tmp/hls/live/;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }
    }

} 

rtmp {

    server{
        listen 1935;
        chunk_size 4096;
        
        # ffmpeg.log used forseeing what is going wrong with the ffmpeg command
        # if it breaks check that
        application live {
            live on;
            record off;
            exec ffmpeg -i rtmp://localhost/live/$name
            -c:v libx264 
            -preset ultrafast
            -c:a aac
            -f hls
            -hls_time 10
            -hls_list_size 15
            -hls_flags delete_segments 
            /tmp/hls/live/$name.m3u8
             2>/tmp/ffmpeg.log; 
        }
    }
}
 
